# Generated by Django 2.1 on 2018-08-11 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='foo',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='domains.Client'),
        ),
    ]
